# Metadata
name: "JoyTag"
id: "joytag"
wrapper_path: "src.wrappers.joytag.JoyTagWrapper"
tags: true
natural_language: false
model_id: "fancyfeast/joytag"
model_path: "fancyfeast/joytag"
description: "Fast tagging model with threshold-based tag generation. Supports Flash Attention for speed improvements. Supports NSFW."
media_type:
  - "Image"
caption_speed: 9.1
licence: "Apache 2.0"
licence-url: "https://choosealicense.com/licenses/apache-2.0/"

# Supported features
features:
  - threshold

# Defaults
defaults:
  threshold: 0.4
  token_length: 100

# VRAM recommendations
vram_table:
  4: 32
  6: 72
  8: 90
  12: 192
  16: 300
  24: 448
  32: 640

# Feature layout
feature_rows:
  - [threshold]
