# Metadata
name: "Moondream 2"
id: "moondream2"
wrapper_path: "src.wrappers.moondream2.Moondream2Wrapper"
tags: false
natural_language: true
model_path: "vikhyatk/moondream2"
description: "Small 2B parameter model, supports Query Mode to ask a question about the image instead of getting a captioning-like response. <b>Batch size has no effect</b>"
media_type:
  - "Image"
caption_speed: 0.6
licence: "Apache 2.0"
licence-url: "https://choosealicense.com/licenses/apache-2.0/"

# Model processes images sequentially - batch_size has no effect
# hide_batch_size: true
# Showing batch size anyway as it's still an indicator for minimum batch size.

# Supported features
features:
  - model_mode
  - task_prompt
  - prompt_source
  - prompt_presets

# Model Modes
model_modes:
  - Caption
  - Query

# Defaults
defaults:
  max_tokens: 512
  model_mode: "Caption"
  prompt_source: "Prompt Presets"
  prompt_presets: "Detailed Caption"

# Prompt Presets
prompt_presets:
  Brief Caption: "Describe briefly."
  Detailed Caption: "Describe this image in detail."
  Analysis: "Analyze the visual elements and their relationships."
  Count: "How many [THING] are in this image?"

# VRAM recommendations
vram_table:
  8: 1

# Feature layout
feature_rows:
  - preset: mode_prompt_control
  - preset: prompt_input
  - preset: file_metadata

