# Metadata
name: "Pixtral 12B"
id: "pixtral_12b"
wrapper_path: "src.wrappers.pixtral_12b.Pixtral12BWrapper"
tags: false
natural_language: true
model_path: "mistralai/Pixtral-12B-2409"
description: "12B parameter model with excellent text and prompt understanding."
media_type:
  - "Image"
caption_speed: 0.17
licence: "Apache 2.0"
licence-url: "https://choosealicense.com/licenses/apache-2.0/"

# Supported features
features:
  - model_version
  - temperature
  - top_k
  - repetition_penalty
  - task_prompt
  - prompt_presets
  - prompt_source
  - prompt_prefix
  - prompt_suffix
  - prompt_file_extension
  - system_prompt

# Defaults
defaults:
  max_tokens: 512
  temperature: 0.7
  top_k: 50
  repetition_penalty: 1.5
  max_width: 1024
  max_height: 1024
  prompt_source: "Prompt Presets"
  system_prompt: "You are a helpful assistant."
  model_version: "Quantized (nf4)"
  prompt_presets: "Long Description"

# Model version
model_versions:
  "Quantized (nf4)": "SeanScripts/pixtral-12b-nf4"
  "Full Model": "mistral-community/pixtral-12b"

# Prompt presets
prompt_presets:
  "Comma Separated Tags": "return tags only, 10 tags"
  "Short Caption": "Describe the in one sentence"
  "Medium Description": "Caption with a short description"
  "Long Description": "Caption this image"
  "Very Long Description": "Describe everything about this image in detail without formatting"

# VRAM recommendations
vram_table:
  "Quantized (nf4)":
    16: 2
    24: 5
    32: 9
  "Full Model":
    24: 1
    32: 2

# Feature layout
feature_rows:
  - preset: sampling_params
  - preset: system_and_prompt_control
  - preset: prompt_input
  - preset: file_metadata

