# Metadata
name: "SmolVLM"
id: "smolVLM"
wrapper_path: "src.wrappers.smolvlm.SmolVLMWrapper"
tags: false
natural_language: true
model_path: "HuggingFaceTB/SmolVLM-Instruct"
description: "Fast and efficient (256M or 500M)."
media_type:
  - "Image"
caption_speed: 1.5
licence: "Apache 2.0"
licence-url: "https://choosealicense.com/licenses/apache-2.0/"

# Supported features
features:
  - model_version
  - task_prompt
  - prompt_presets
  - prompt_source
  - prompt_prefix
  - prompt_suffix
  - prompt_file_extension

# Defaults
defaults:
  max_tokens: 512
  temperature: 0.7
  top_k: 50
  repetition_penalty: 1.1
  model_version: "500M"
  prompt_source: "Prompt Presets"
  prompt_presets: "Detailed Caption"

# Model version
model_versions:
  "256M": "HuggingFaceTB/SmolVLM-256M-Instruct"
  "500M": "HuggingFaceTB/SmolVLM-500M-Instruct"

# Prompt presets
prompt_presets:
  Comma Separated Tags: "Describe the image in one sentence"
  Short Caption: "Describe the image in one sentence"
  Medium Caption: "Caption with a short description"
  Detailed Caption: "Caption this image"
  Very Detailed Caption: "Describe everything about this image in detail without formatting"
  Tags: "List the key elements in this image as a couple of comma-separated tags"

# VRAM Recommendations
vram_table:
  "256M":
    4: 2
    8: 10
    12: 20
    16: 28
    24: 46
    32: 64
  "500M":
    4: 2
    8: 10
    12: 20
    16: 28
    24: 46
    32: 64

# Feature layout
feature_rows:
  - preset: prompt_control
  - preset: prompt_input
  - preset: file_metadata
