# Metadata
name: "SmolVLM 2"
id: "smolVLM2"
wrapper_path: "src.wrappers.smolvlm2.SmolVLM2Wrapper"
tags: false
natural_language: true
model_path: "HuggingFaceTB/SmolVLM2-2.2B-Instruct"
description: "Fast and efficient model supporting images and videos (256M, 500M, 2.2B)."
media_type: 
  - "Image"
  - "Video"
caption_speed: 2
licence: "Apache 2.0"
licence-url: "https://choosealicense.com/licenses/apache-2.0/"

# Supported features
features:
  - model_version
  - task_prompt
  - prompt_presets
  - prompt_source
  - prompt_prefix
  - prompt_suffix
  - prompt_file_extension
  - system_prompt

# Defaults
defaults:
  max_tokens: 512
  model_version: "500M"
  system_prompt: "You are a helpful assistant."
  prompt_source: "Prompt Presets"
  prompt_presets: "Detailed Caption"

# Model versions
model_versions:
  "256M": "HuggingFaceTB/SmolVLM2-256M-Video-Instruct"  
  "500M": "HuggingFaceTB/SmolVLM2-500M-Video-Instruct"
  "2.2B": "HuggingFaceTB/SmolVLM2-2.2B-Instruct"

# Prompt presets
prompt_presets:
  Detailed Caption: "Describe this in detail, focusing on main events and actions."
  Short Caption: "Summarize the in one sentence."
  List Objects: "List the main objects visible."

# VRAM recommendations
vram_table:
  "256M":
    4: 2
    8: 12
    12: 24
    16: 36
    24: 56
    32: 80
  "500M":
    4: 2
    8: 12
    12: 24
    16: 36
    24: 56
    32: 80
  "2.2B":
    8: 4
    12: 16
    16: 20
    24: 48
    32: 70

# Feature layout
feature_rows:
  - preset: system_and_prompt_control
  - preset: prompt_input
  - preset: file_metadata
