services:
  athousandwords:
    build: .
    image: athousandwords:latest
    ports:
      - "7860:7860"  # Gradio GUI
      - "8000:8000"  # API (optional)
    volumes:
      - ./user:/app/user  # Persist user config and uploads
      - ./input:/app/input  # Mount input directory
     #- ./models:/app/models # Persist Hugging Face cache/models
      - ./src:/app/src
      - ./gui.py:/app/gui.py
      - ./captioner.py:/app/captioner.py
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - HF_HOME=/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
